# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# An example of a pod using the node cache. Change the node selector to use
# different kinds of caches.
kind: Pod
apiVersion: v1
metadata:
  name: example
spec:
  terminationGracePeriodSeconds: 1
  nodeSelector:
    node-cache.gke.io: pd
  containers:
  - name: debian
    image: debian
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: cache
      mountPath: /cache
  volumes:
  - name: cache
    csi:
      driver: node-cache.csi.storage.gke.io
